tests/test-eds-ics-missing-trigger.cpp: Include engine-eds.h prio to alarm-queue-simple.h.
 Addresses this issue occuring when building with clang++:

 /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:150:23: error: no matching constructor for initialization of 'ayatana::indicator::datetime::EdsEngine'
        { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }